=== Dragmoria/CsvLogger/CsvLogger/Data/Schema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="schema">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="column" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="name" type="xs:string" use="required" />
						<xs:attribute name="type" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="s" />
									<xs:enumeration value="i" />
									<xs:enumeration value="b" />
									<xs:enumeration value="d" />
									<xs:enumeration value="dt" />
									<xs:enumeration value="dec" />
									<xs:enumeration value="g" />
									<xs:enumeration value="f" />
									<xs:enumeration value="c" />
									<xs:enumeration value="l" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Dragmoria/CsvLogger/CsvLogger.Tests/Data/ValidTestCsvSchema.xml
<?xml version="1.0" encoding="utf-8" ?>
<schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="schema.xsd">
	<column name="StartDateTime" type="dt" />
	<column name="EndDateTime" type="dt" />
	<column name="Identifier" type="g" />
	<column name="Field1" type="s" />
	<column name="Field2" type="i" />
	<column name="Field3" type="b" />
	<column name="Field4" type="d" />
	<column name="Field5" type="dec" />
	<column name="Field6" type="f" />
	<column name="Field7" type="c" />
	<column name="Field8" type="l" />
</schema>
